apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-pipeline-runner
  namespace: kubeflow-user-example-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fraud-pipeline-runner
  namespace: kubeflow-user-example-com
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "create", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fraud-pipeline-runner
  namespace: kubeflow-user-example-com
subjects:
  - kind: ServiceAccount
    name: fraud-pipeline-runner
    namespace: kubeflow-user-example-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fraud-pipeline-runner
