apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: scored-transactions
  namespace: kafka
  labels:
    strimzi.io/cluster: platform-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "86400000"
    cleanup.policy: delete
