apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flink-system
resources:
  - resources.yaml
  - kafka-topic-scored-transactions.yaml
configMapGenerator:
  - name: flink-streaming-sql
    files:
      - flink_streaming_job.sql
    options:
      disableNameSuffixHash: true
  - name: flink-scored-ddl
    files:
      - flink_scored_ddl.sql
    options:
      disableNameSuffixHash: true
  - name: flink-scored-kafka-publisher-sql
    files:
      - flink_scored_kafka_publisher.sql
    options:
      disableNameSuffixHash: true
