apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/strimzi
patches:
  - target:
      kind: HelmRelease
      name: strimzi-kafka-operator
    patch: |-
      - op: add
        path: /spec/values
        value:
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
