apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/minio
patches:
  - target:
      kind: HelmRelease
      name: minio
    patch: |-
      - op: add
        path: /spec/values/resources
        value:
          requests:
            cpu: 250m
            memory: 512Mi
