apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/flink-jobs
patches:
  - target:
      kind: FlinkDeployment
      name: sample-fraud-stream
      namespace: flink-system
    patch: |-
      - op: add
        path: /spec/jobManager/podTemplate/spec/containers/0/env/-
        value:
          name: KAFKA_BOOTSTRAP_SERVERS
          value: platform-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
