apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kubeflow
patches:
  - target:
      kind: Kustomization
      name: kubeflow
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/timeout
        value: 30m
      - op: add
        path: /spec/targetNamespace
        value: kubeflow
  - path: kfp-resource-patch.yaml
    target:
      kind: Deployment
      namespace: kubeflow
  - path: kserve-rawdeployment-patch.yaml
    target:
      kind: ConfigMap
      name: inferenceservice-config
      namespace: kserve
