apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flink-kubernetes-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://downloads.apache.org/flink/flink-kubernetes-operator-1.14.0/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flink-kubernetes-operator
  namespace: flink-system
spec:
  interval: 30m
  chart:
    spec:
      chart: flink-kubernetes-operator
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: flink-kubernetes-operator
        namespace: flux-system
  timeout: 10m
  install:
    createNamespace: true
  values:
    watchNamespaces:
      - flink-system
