apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kafka-ui
patches:
  - target:
      kind: HelmRelease
      name: kafka-ui
      namespace: kafka-ui
    patch: |-
      - op: add
        path: /spec/values/service
        value:
          type: NodePort
